source 'https://github.com/CocoaPods/Specs.git'

target 'CoreHound', :exclusive => true do
  pod "AtSugar", :git => "https://github.com/MediaHound/AtSugar.git"
  pod "Avenue", :git => "https://github.com/MediaHound/Avenue.git"
  pod "KVOController", :git => 'https://github.com/facebook/KVOController.git'
  pod "CoreHound", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CoreHound", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
