platform :ios, '8.0'
use_frameworks!

target 'CoreHound', :exclusive => true do
  pod "CoreHound", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CoreHound", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
